In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np 

In [ ]:
#creating a array and checking the type
list1 = np.array([1,2,3])
print(type(list1))



<class 'numpy.ndarray'>


In [17]:
#one dimensional array
array = np.array([1,2,3])
print(array.ndim)
print(array)
print(array.shape)

print()

#two dimensional array
array2 = np.array([[1,2,3],[4,5,6]])
print(array2.ndim)
print(array2)
print(array2.shape)

print()

#three dimensional array
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                   [[10,11,12],[13,14,15],[16,17,18]],
                   [[19,20,21],[22,23,24],[25,26,27]]])

print(array3.ndim)
print(array3)
print(array3.shape)




1
[1 2 3]
(3,)

2
[[1 2 3]
 [4 5 6]]
(2, 3)

3
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)


In [21]:
#indexing 
print(array[:])

print(array2[0][1])
print(array2[1][2])

print(array3[1][1][1])

[1 2 3]
2
6
14


In [25]:
#slicing
l = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

#array[start:stop:step]
print(l[1:3])
print()
print(l[:])
print()
print(l[::2])
print()

#Slicing both row and column 
print(l[1:3, 1:3])

[[4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1 2 3]
 [7 8 9]]

[[5 6]
 [8 9]]


In [28]:
#arithmetic operations

#scalar operations
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a*2)

#basic element-wise operations
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

#builtin mathematical fucntion
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.log10(a))


[2 4 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[  1  32 729]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]


In [29]:
#comparison operators
marks = np.array([45, 80, 65, 70, 90])
print(marks > 50)

[False  True  True  True  True]


In [ ]:
#broadcasting
r = np.array([1,2,3])
s = np.array([4,5,6])
t = r + s
p = r * s
print(t)
print(p)

#examples of positive broadcasting
r = np.array([1,2,3])
s = np.array([[2],[2],[2]])
t = r + s
print(t)

#failure of broadcasting
r = np.array([[1,2,3],[3,2,4]])
s = np.array([[2],[2],[2]])
t = r + s
print(t)

[5 7 9]
[ 4 10 18]
[[3 4 5]
 [3 4 5]
 [3 4 5]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [ ]:
#aggregation functions
k = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(k.sum())
print(k.max())
print(k.min())
print(k.mean())
print(k.var())
print(k.std())

#setting axis
print(k.sum(axis=0)) #column
print(k.sum(axis=1)) #row




50
9
1
5.0
6.0
2.449489742783178


In [39]:
#Filtering
ages = np.array([23, 45, 67, 89, 12, 34, 56, 78, 90])
print(ages)

print()

teenager = ages[ages<18]
adult = ages[ages>=18]
print(teenager)
print(adult)

#preserving original shape of array
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
v = np.where(b>5,b,b*10)
print(v)



[23 45 67 89 12 34 56 78 90]

[12]
[23 45 67 89 34 56 78 90]
[[10 20 30 40 50]
 [ 6  7  8  9 10]]


In [48]:
#random number generator
rng = np.random.default_rng()
print(rng.integers(1,10, size=(3,3)))
print()

#with seed
rng = np.random.default_rng(42)
print(rng.integers(1,10, size=(3,3)))
print()

#uniform
print(np.random.uniform(1,10, size=(3,3)))

#shuffle
rng = np.random.default_rng()
u = np.array([1,2,3,4,5,6,7,8,9,10])
rng.shuffle(u)
print(u)

fruits = np.array(["apple", "banana", "cherry","pineapple","orange","musk melon","watermelon"])
fruit = rng.choice(fruits , (3,3))
print(fruit)


[[8 1 8]
 [8 2 8]
 [3 5 7]]

[[1 7 6]
 [4 4 8]
 [1 7 2]]

[[3.6979469  4.60998764 7.92272275]
 [3.38547163 6.82106594 3.18377262]
 [5.98961174 5.18095547 1.34077622]]
[ 4  8  6  3  7  1  9 10  5  2]
[['banana' 'orange' 'cherry']
 ['banana' 'apple' 'apple']
 ['banana' 'watermelon' 'apple']]
