In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np 

In [ ]:
#creating a array and checking the type
list1 = np.array([1,2,3])
print(type(list1))



<class 'numpy.ndarray'>


In [17]:
#one dimensional array
array = np.array([1,2,3])
print(array.ndim)
print(array)
print(array.shape)

print()

#two dimensional array
array2 = np.array([[1,2,3],[4,5,6]])
print(array2.ndim)
print(array2)
print(array2.shape)

print()

#three dimensional array
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                   [[10,11,12],[13,14,15],[16,17,18]],
                   [[19,20,21],[22,23,24],[25,26,27]]])

print(array3.ndim)
print(array3)
print(array3.shape)




1
[1 2 3]
(3,)

2
[[1 2 3]
 [4 5 6]]
(2, 3)

3
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)


In [21]:
#indexing 
print(array[:])

print(array2[0][1])
print(array2[1][2])

print(array3[1][1][1])

[1 2 3]
2
6
14


In [25]:
#slicing
l = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

#array[start:stop:step]
print(l[1:3])
print()
print(l[:])
print()
print(l[::2])
print()

#Slicing both row and column 
print(l[1:3, 1:3])

[[4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1 2 3]
 [7 8 9]]

[[5 6]
 [8 9]]
